

const HANDLING_DATA: [&str, {HANDLING__REPLACE_POINT_len};] = {HANDLING__REPLACE_POINT};
const RANGE_DATA:    [&str, {RANGE_REPLACE_POINT_len};] = {RANGE_REPLACE_POINT};
const RELOAD_DATA:   [&str, {RELOAD_REPLACE_POINT_len};] = {RELOAD_REPLACE_POINT};
const SCALAR_DATA:   [&str, {SCALAR_REPLACE_POINT_len};] = {SCALAR_REPLACE_POINT};
const FIRING_DATA:   [&str, {FIRING_REPLACE_POINT_len};] = {FIRING_REPLACE_POINT};
const AMMO_DATA:     [&str, {AMMO_REPLACE_POINT_len};] = {AMMO_REPLACE_POINT};